### PR TITLE
Smart size transformation

### PR DESCRIPTION
**Pull request by kbrabrand**
This PR adds a "smart size" transformation to imbo. The transformation takes a desired width and height, and a POI (point-of-interest) coordinate parameter – (x,y). Based on these three parameter Imbo crops the image, trying to center the poi in the process.

There are a few possible improvements here:
1. Support multiple POIs
2. Get POI from metadata if not specified as a query param
3. Look into the possibility of closer crops, if desirable

### CODE REVIEW

**Comment by kbrabrand** [comment]
This PR is work-in-progress. I'd like to add support for getting the POI from metadata before this is merged.

**Comment by kbrabrand** [comment]
With the last commit I think we're pretty close to what we want. It now crops around the POI using a grow factor that grows the area, and then it has a threshold value that ensures that the width/height of the area used when cropping is never less than a given percentage of the source width/height. 

This way we have a way of cropping a bit closer – how close is possible to set using the `crop` param – and at the same time avoid making useless crops of just a nose when focusing on a face in a really high-res image.

**Comment by rexxars** [comment]
This looks great. I'd like to see some integration tests added, however - just for sanity checks. For instance, a couple of simple PNGs with a few areas meant to be the POI in a different color, then use the transformation and ensure certain coordinates have the expected color values.

Before we merge this, I really want to fetch the POI(s) from metadata, if not passed explicitly.

Support for multiple POIs would be interesting as well. Thoughts?

**Comment by kbrabrand** [comment]
I'll add the integration tests and fetching from metadata tomorrow.

Multiple POIs however is a bit more tricky. Simply creating a minimum bounding box that all the POIs fits within and cropping around that is too naïve and will give worse results in lots of cases. So I think sticking to a fairly simple, but functioning one-POI-solution is better than going for a half assed multiple POI solution. The algorithm required to determine how the crop should be done factoring in how to best include, or exclude, POIs is not trivial.

**Pull request merged**
