### PR TITLE
Add new mongo database adapter

### PR DESCRIPTION
**Pull request by bjarneo**
- Added a new mongo adapter to support the new driver. Much needed for MongoDB 3.2. https://docs.mongodb.org/ecosystem/drivers/php/
- Used this abstraction https://github.com/mongodb/mongo-php-library

Can change the class name to something else that suits this adapter better than "mongo".

### CODE REVIEW

**Comment by bjarneo** [comment]
Problem 1
    - Installation request for doctrine/cache v1.6.0 -> satisfiable by doctrine/cache[v1.6.0].
    - doctrine/cache v1.6.0 requires php ~5.5|~7.0 -> your PHP version (5.4.45) does not satisfy that requirement.
  Problem 2
    - Installation request for doctrine/common v2.6.1 -> satisfiable by doctrine/common[v2.6.1].
    - doctrine/common v2.6.1 requires php ~5.5|~7.0 -> your PHP version (5.4.45) does not satisfy that requirement.
  Problem 3
    - Installation request for symfony/filesystem v3.0.2 -> satisfiable by symfony/filesystem[v3.0.2].
    - symfony/filesystem v3.0.2 requires php >=5.5.9 -> your PHP version (5.4.45) does not satisfy that requirement.
  Problem 4
    - symfony/filesystem v3.0.2 requires php >=5.5.9 -> your PHP version (5.4.45) does not satisfy that requirement.
    - symfony/config v2.8.2 requires symfony/filesystem ~2.3|~3.0.0 -> satisfiable by symfony/filesystem[v3.0.2].
    - Installation request for symfony/config v2.8.2 -> satisfiable by symfony/config[v2.8.2]

Take doctrine, sub packages have require like this:  "doctrine/cache": "1.*"
Should I downgrade doctrine package? Or drop PHP 5.4 support? (troll face)

**Comment by rexxars** [comment]
I actually started the same thing quite a while ago: https://github.com/imbo/imbo/issues/403#issuecomment-162590520

I was holding of until GridFS support was in place, but I guess in many cases using Mongo + filesystem/S3 would still benefit from this.

I don't have time to look this over right now, but I'll see if I have time to compare the two branches later today.

**Comment by bjarneo** [comment]
Alright.

I didn't know it was a database class in Imbo\EventListener\ImageVariations\Database also.

**Comment by bjarneo** [comment]
So what's the approach now? 

Since you already created this I don't think I need to update the PR with the ImageVariations database. 

If this PR should be used I need to:
Move my changes to MongoDB.php and remove Mongo.php (newly created)
Update the image variations database mongo class.
Fix the (array) approach.

**Comment by rexxars** [comment]
I guess if you don't mind we can go ahead and merge my version. Just a little unsure about the naming, but I guess `mongo` vs `mongodb` works for now? Preferably I'd like to make an adapter that checks which extension is installed and uses the one suited for the environment, but I don't have time to do that currently.

**Comment by bjarneo** [comment]
I don't mind. We're upgrading mongodb to 3.2, so we just need support for the new driver.

Mongo should work just fine.

**Pull request closed without merging**
